//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.IO;
using System.IO.IsolatedStorage;
using System.Linq;
using System.Reflection;
using derpirc.Data.Models.Settings;

namespace derpirc.Data
{
    public partial class SettingsModelContainer : System.Data.Linq.DataContext
    {
        public static string ConnectionString = "Data Source=isostore:/Settings.sdf";

        public static string FileName = "Settings.sdf";

        public SettingsModelContainer(string connectionString)
            : base(connectionString)
        {
            OnCreated();
        }

        public bool CreateIfNotExists()
        {
            bool created = false;
            using (var db = new SettingsModelContainer(SettingsModelContainer.ConnectionString))
            {
                if (!db.DatabaseExists())
                {
                    string[] names = this.GetType().Assembly.GetManifestResourceNames();
                    string name = names.Where(n => n.EndsWith(FileName)).FirstOrDefault();
                    if (name != null)
                    {
                        using (Stream resourceStream = Assembly.GetExecutingAssembly().GetManifestResourceStream(name))
                        {
                            if (resourceStream != null)
                            {
                                using (IsolatedStorageFile myIsolatedStorage = IsolatedStorageFile.GetUserStoreForApplication())
                                {
                                    using (IsolatedStorageFileStream fileStream = new IsolatedStorageFileStream(FileName, System.IO.FileMode.Create, myIsolatedStorage))
                                    {
                                        using (BinaryWriter writer = new BinaryWriter(fileStream))
                                        {
                                            long length = resourceStream.Length;
                                            byte[] buffer = new byte[32];
                                            int readCount = 0;
                                            using (BinaryReader reader = new BinaryReader(resourceStream))
                                            {
                                                // read file in chunks in order to reduce memory consumption and increase performance
                                                while (readCount < length)
                                                {
                                                    int actual = reader.Read(buffer, 0, buffer.Length);
                                                    readCount += actual;
                                                    writer.Write(buffer, 0, actual);
                                                }
                                            }
                                        }
                                    }
                                }
                                created = true;
                            }
                            else
                            {
                                db.CreateDatabase();
                                created = true;
                            }
                        }
                    }
                    else
                    {
                        db.CreateDatabase();
                        created = true;
                    }
                }
            }
            return created;
        }

        #region Extensibility Method Definitions
        partial void OnCreated();
        partial void InsertFormatting(Formatting instance);
        partial void UpdateFormatting(Formatting instance);
        partial void DeleteFormatting(Formatting instance);
        partial void InsertNetwork(Network instance);
        partial void UpdateNetwork(Network instance);
        partial void DeleteNetwork(Network instance);
        partial void InsertServer(Server instance);
        partial void UpdateServer(Server instance);
        partial void DeleteServer(Server instance);
        partial void InsertSession(Session instance);
        partial void UpdateSession(Session instance);
        partial void DeleteSession(Session instance);
        partial void InsertStorage(Storage instance);
        partial void UpdateStorage(Storage instance);
        partial void DeleteStorage(Storage instance);
        partial void InsertUser(User instance);
        partial void UpdateUser(User instance);
        partial void DeleteUser(User instance);
        #endregion

        #region Table Properties

        public System.Data.Linq.Table<Favorite> Favorites
        {
            get
            {
                return this.GetTable<Favorite>();
            }
        }

        public System.Data.Linq.Table<Formatting> Formattings
        {
            get
            {
                return this.GetTable<Formatting>();
            }
        }

        public System.Data.Linq.Table<Network> Networks
        {
            get
            {
                return this.GetTable<Network>();
            }
        }

        public System.Data.Linq.Table<Server> Servers
        {
            get
            {
                return this.GetTable<Server>();
            }
        }

        public System.Data.Linq.Table<Session> Sessions
        {
            get
            {
                return this.GetTable<Session>();
            }
        }

        public System.Data.Linq.Table<Storage> Storages
        {
            get
            {
                return this.GetTable<Storage>();
            }
        }

        public System.Data.Linq.Table<User> Users
        {
            get
            {
                return this.GetTable<User>();
            }
        }

        #endregion

        #region Method Overrides

        public void InitializeDatabase()
        {
            using (IsolatedStorageFile iso = IsolatedStorageFile.GetUserStoreForApplication())
            {
                if (iso.FileExists(FileName))
                    return;

                CreateDatabase();
            }
        }

        public void InitializeDatabase(bool wipe)
        {
            using (IsolatedStorageFile iso = IsolatedStorageFile.GetUserStoreForApplication())
            {
                if (wipe)
                    WipeDatabase(iso);
                else
                {
                    if (iso.FileExists(FileName))
                        return;
                }

                CreateDatabase();
            }
        }

        private new void CreateDatabase()
        {
            try
            {
                // Generate the database (with structure) from the code-based data context
                base.CreateDatabase();

                // Populate the database with system data
                GenerateSystemData();
            }
            catch (Exception ex)
            {
                //MessageBox.Show("Error while creating the DB: " + ex.Message);
                System.Diagnostics.Debug.WriteLine("Error while creating the DB: " + ex.Message);
            }
        }

        public void WipeDatabase(IsolatedStorageFile iso)
        {
            if (iso.FileExists(FileName))
                iso.DeleteFile(FileName);
        }

        public bool DatabaseExists(bool overrideResult = false)
        {
            if (!overrideResult)
            {
                using (IsolatedStorageFile iso = IsolatedStorageFile.GetUserStoreForApplication())
                {
                    if (iso.FileExists(FileName))
                        return true;
                    else
                        return false;
                }
            }
            else
                return false;
        }

        private void GenerateSystemData()
        {
            var user = Factory.CreateUser();
            this.Users.InsertOnSubmit(user);
            this.SubmitChanges();

            var formatting = Factory.CreateFormatting();
            this.Formattings.InsertOnSubmit(formatting);
            this.SubmitChanges();

            var session = Factory.CreateSession();
            this.Sessions.InsertOnSubmit(session);
            this.SubmitChanges();

            var storage = Factory.CreateStorage();
            this.Storages.InsertOnSubmit(storage);
            this.SubmitChanges();
        }

        #endregion

    }
}