//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace derpirc.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("derpirc.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback or pony requests: .
        /// </summary>
        public static string AboutFeedbackDescription {
            get {
                return ResourceManager.GetString("AboutFeedbackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to derpirc-feedback@braytonium.com.
        /// </summary>
        public static string AboutFeedbackEmail {
            get {
                return ResourceManager.GetString("AboutFeedbackEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m about to tell you how to make an app. Ready?.
        /// </summary>
        public static string AboutFeedbackEmailSubject {
            get {
                return ResourceManager.GetString("AboutFeedbackEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stroke my ego, plz: .
        /// </summary>
        public static string AboutReviewDescription {
            get {
                return ResourceManager.GetString("AboutReviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review this (cr)app.
        /// </summary>
        public static string AboutReviewURLText {
            get {
                return ResourceManager.GetString("AboutReviewURLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support:.
        /// </summary>
        public static string AboutSupport {
            get {
                return ResourceManager.GetString("AboutSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to derpirc-support@braytonium.com.
        /// </summary>
        public static string AboutSupportEmail {
            get {
                return ResourceManager.GetString("AboutSupportEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WP7.
        /// </summary>
        public static string AboutSupportSubject {
            get {
                return ResourceManager.GetString("AboutSupportSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: .
        /// </summary>
        public static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forged in the bowels of insanity by Braytonium Software.
        /// </summary>
        public static string AboutWebsiteDescription {
            get {
                return ResourceManager.GetString("AboutWebsiteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to braytonium.com/derpirc/.
        /// </summary>
        public static string AboutWebsiteURLText {
            get {
                return ResourceManager.GetString("AboutWebsiteURLText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to derpirc.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connections.
        /// </summary>
        public static string Connections {
            get {
                return ResourceManager.GetString("Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cellular settings.
        /// </summary>
        public static string ConnectionsAppBarCellularSettings {
            get {
                return ResourceManager.GetString("ConnectionsAppBarCellularSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connect.
        /// </summary>
        public static string ConnectionsAppBarConnect {
            get {
                return ResourceManager.GetString("ConnectionsAppBarConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disconnect.
        /// </summary>
        public static string ConnectionsAppBarDisconnect {
            get {
                return ResourceManager.GetString("ConnectionsAppBarDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reconnect.
        /// </summary>
        public static string ConnectionsAppBarReconnect {
            get {
                return ResourceManager.GetString("ConnectionsAppBarReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        public static string ConnectionsAppBarSelect {
            get {
                return ResourceManager.GetString("ConnectionsAppBarSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wifi settings.
        /// </summary>
        public static string ConnectionsAppBarWifiSettings {
            get {
                return ResourceManager.GetString("ConnectionsAppBarWifiSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected via: .
        /// </summary>
        public static string ConnectionsStatus {
            get {
                return ResourceManager.GetString("ConnectionsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to channels.
        /// </summary>
        public static string MainChannels {
            get {
                return ResourceManager.GetString("MainChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mentions.
        /// </summary>
        public static string MainMentions {
            get {
                return ResourceManager.GetString("MainMentions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to messages.
        /// </summary>
        public static string MainMessages {
            get {
                return ResourceManager.GetString("MainMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to network.
        /// </summary>
        public static string NetworkDetail {
            get {
                return ResourceManager.GetString("NetworkDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string NetworkDetailAppBarDelete {
            get {
                return ResourceManager.GetString("NetworkDetailAppBarDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Name.
        /// </summary>
        public static string NetworkDetailHostName {
            get {
                return ResourceManager.GetString("NetworkDetailHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NetworkDetailName {
            get {
                return ResourceManager.GetString("NetworkDetailName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string NetworkDetailPassword {
            get {
                return ResourceManager.GetString("NetworkDetailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string NetworkDetailPort {
            get {
                return ResourceManager.GetString("NetworkDetailPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to server information.
        /// </summary>
        public static string NetworkDetailServerInfo {
            get {
                return ResourceManager.GetString("NetworkDetailServerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string NetworkTypeData {
            get {
                return ResourceManager.GetString("NetworkTypeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethernet.
        /// </summary>
        public static string NetworkTypeEthernet {
            get {
                return ResourceManager.GetString("NetworkTypeEthernet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string NetworkTypeNone {
            get {
                return ResourceManager.GetString("NetworkTypeNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string NetworkTypeUnknown {
            get {
                return ResourceManager.GetString("NetworkTypeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireless.
        /// </summary>
        public static string NetworkTypeWireless {
            get {
                return ResourceManager.GetString("NetworkTypeWireless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string ProgressLoading {
            get {
                return ResourceManager.GetString("ProgressLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string SettingsAppBarAdd {
            get {
                return ResourceManager.GetString("SettingsAppBarAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear.
        /// </summary>
        public static string SettingsAppBarClear {
            get {
                return ResourceManager.GetString("SettingsAppBarClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to client.
        /// </summary>
        public static string SettingsClient {
            get {
                return ResourceManager.GetString("SettingsClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry disconnects.
        /// </summary>
        public static string SettingsClientDisconnectRetries {
            get {
                return ResourceManager.GetString("SettingsClientDisconnectRetries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry waiting period (seconds).
        /// </summary>
        public static string SettingsClientDisconnectRetriesWait {
            get {
                return ResourceManager.GetString("SettingsClientDisconnectRetriesWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join on Invite.
        /// </summary>
        public static string SettingsClientJoinOnInvite {
            get {
                return ResourceManager.GetString("SettingsClientJoinOnInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect on Disconnect.
        /// </summary>
        public static string SettingsClientReconnectOnDisconnect {
            get {
                return ResourceManager.GetString("SettingsClientReconnectOnDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejoin on Kick.
        /// </summary>
        public static string SettingsClientRejoinOnKick {
            get {
                return ResourceManager.GetString("SettingsClientRejoinOnKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formatting.
        /// </summary>
        public static string SettingsFormatting {
            get {
                return ResourceManager.GetString("SettingsFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to networks.
        /// </summary>
        public static string SettingsNetworks {
            get {
                return ResourceManager.GetString("SettingsNetworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to storage.
        /// </summary>
        public static string SettingsStorage {
            get {
                return ResourceManager.GetString("SettingsStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate.
        /// </summary>
        public static string SettingsUserAlternate {
            get {
                return ResourceManager.GetString("SettingsUserAlternate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string SettingsUserFullName {
            get {
                return ResourceManager.GetString("SettingsUserFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invisible.
        /// </summary>
        public static string SettingsUserInvisible {
            get {
                return ResourceManager.GetString("SettingsUserInvisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NickName.
        /// </summary>
        public static string SettingsUserNickName {
            get {
                return ResourceManager.GetString("SettingsUserNickName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Message.
        /// </summary>
        public static string SettingsUserQuitMessage {
            get {
                return ResourceManager.GetString("SettingsUserQuitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string SettingsUserUsername {
            get {
                return ResourceManager.GetString("SettingsUserUsername", resourceCulture);
            }
        }
    }
}
